# INFO
# The data for this script is generated by analytics.py

library('MASS')

########################################
## Duration ############################
########################################
data = read.csv('C:/temp/migration-times.csv', sep='\t')

# Descriptive statistics
times.elements = length(data$duration)
times.duration = mean(data$duration)
times.quantiles = quantile(data$duration)

# Fit and plot log-normal distribution
y = data$duration
params = fitdistr(y, densfun="log-normal")

x = seq(0,100)
hist(y, main=NULL, xlab="Migration duration", ylab="Probability", prob=TRUE)
hx = dlnorm(x=x, meanlog=3.3, sdlog=0.27)
lines(x, hx, col='red', lwd=3)

cat('length:', times.elements, ' mean duration:', times.duration, ' quantiles:', times.quantiles)
print('Log normal distribution params:')
print(params)

########################################
## Migration Data ######################
########################################
data = read.csv('C:/temp/migration-data.csv', sep='\t')

# Descriptive statistics on migration errors
mean(data$errors)
errors.none = length(data$errors[data$errors == 0])
errors.count = length(data$errors)
errors.per = errors.none / errors.count
cat(round(errors.per * 100, digits=0),'% migrations without errors', sep='')

errors.quantiles = quantile(data$errors, c(.95))
cat('Quantile 95th on number of errors (95% of live migrations <= value): ', errors.quantiles, sep='')

#####################################
# Network Overhead ##################
#####################################
source.diff = (data$source.net.during - data$source.net.before) / 1024 # Convert to MByte/second
hist(source.diff, main='Network Source Server', xlab='Traffic increase before - during migration')

source.mean = mean(source.diff)
source.median = median(source.diff)
cat("Network - source server: ", "mean = ", round(source.mean, digits=2), " median = ", round(source.median, digits=2), sep='')

target.diff = (data$target.net.during - data$target.net.before) / 1024
hist(target.diff, main='Network Target Server', xlab='Traffic increase before - during migration')
target.mean = mean(target.diff)
target.median = median(target.diff)
cat("Network - target server: ", "mean = ", round(target.mean, digits=2), " median = ", round(target.median, digits=2), sep='')

#####################################
# CPU Overhad #######################
#####################################
data = read.csv('C:/temp/migration-data.csv', sep='\t')
source.diff = data$source.during - data$source.before
hist(source.diff, main='CPU Source Server', xlab='Load increase before - during migration')

source.diff = source.diff[is.finite(source.diff)] # Filter NaN
source.mean = mean(source.diff)
source.median = median(source.diff)
cat("CPU - source server: ", "mean = ", round(source.mean, digits=2), " median = ", round(source.median, digits=2), sep='')

target.diff = (data$target.during - data$target.before) 
hist(target.diff, main='CPU Target Server', xlab='Load increase before - during migration')

target.diff = target.diff[is.finite(target.diff)]
target.mean = mean(target.diff)
target.median = median(target.diff)
cat("CPU - target server: ", "mean = ", round(target.mean, digits=2), " median = ", round(target.median, digits=2), sep='')

#####################################
# Migration Model ###################
#####################################
data = read.csv('C:/temp/migration-data.csv', sep='\t')
overhead = (data$source.during - data$source.before)
domainload = data$domain.cpu.before


plot(domainload, overhead)

fit = lm(overhead ~ domainload)
abline(fit, col='red')
#hist(residuals(fit))
summary(fit)

domainload2 = data$domain.cpu.before
print(fit)


plot(domainload2, domainload)

fit2 = lm(domainload ~ domainload2)
abline(fit2, col='red')
hist(residuals(fit2))


plot(domainload, data$duration)

fit = lm(data$duration ~ domainload)


