//
// Autogenerated by Thrift Compiler (0.8.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;

var ttypes = require('./collector_types');
//HELPER FUNCTIONS AND STRUCTURES

var ManagementService_query_args = function(args) {
  this.query = null;
  if (args) {
    if (args.query !== undefined) {
      this.query = args.query;
    }
  }
};
ManagementService_query_args.prototype = {};
ManagementService_query_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.query = new ttypes.TimeSeriesQuery();
        this.query.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ManagementService_query_args.prototype.write = function(output) {
  output.writeStructBegin('ManagementService_query_args');
  if (this.query) {
    output.writeFieldBegin('query', Thrift.Type.STRUCT, 1);
    this.query.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ManagementService_query_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
ManagementService_query_result.prototype = {};
ManagementService_query_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size40 = 0;
        var _rtmp344;
        this.success = [];
        var _etype43 = 0;
        _rtmp344 = input.readListBegin();
        _etype43 = _rtmp344.etype;
        _size40 = _rtmp344.size;
        for (var _i45 = 0; _i45 < _size40; ++_i45)
        {
          var elem46 = null;
          elem46 = new ttypes.TransferableTimeSeriesPoint();
          elem46.read(input);
          this.success.push(elem46);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ManagementService_query_result.prototype.write = function(output) {
  output.writeStructBegin('ManagementService_query_result');
  if (this.success) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter47 in this.success)
    {
      if (this.success.hasOwnProperty(iter47))
      {
        iter47 = this.success[iter47];
        iter47.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ManagementService_fetchSensor_args = function(args) {
  this.name = null;
  if (args) {
    if (args.name !== undefined) {
      this.name = args.name;
    }
  }
};
ManagementService_fetchSensor_args.prototype = {};
ManagementService_fetchSensor_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.name = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ManagementService_fetchSensor_args.prototype.write = function(output) {
  output.writeStructBegin('ManagementService_fetchSensor_args');
  if (this.name) {
    output.writeFieldBegin('name', Thrift.Type.STRING, 1);
    output.writeString(this.name);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ManagementService_fetchSensor_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
ManagementService_fetchSensor_result.prototype = {};
ManagementService_fetchSensor_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ManagementService_fetchSensor_result.prototype.write = function(output) {
  output.writeStructBegin('ManagementService_fetchSensor_result');
  if (this.success) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ManagementService_deploySensor_args = function(args) {
  this.name = null;
  this.file = null;
  if (args) {
    if (args.name !== undefined) {
      this.name = args.name;
    }
    if (args.file !== undefined) {
      this.file = args.file;
    }
  }
};
ManagementService_deploySensor_args.prototype = {};
ManagementService_deploySensor_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.name = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.file = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ManagementService_deploySensor_args.prototype.write = function(output) {
  output.writeStructBegin('ManagementService_deploySensor_args');
  if (this.name) {
    output.writeFieldBegin('name', Thrift.Type.STRING, 1);
    output.writeString(this.name);
    output.writeFieldEnd();
  }
  if (this.file) {
    output.writeFieldBegin('file', Thrift.Type.STRING, 2);
    output.writeString(this.file);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ManagementService_deploySensor_result = function(args) {
};
ManagementService_deploySensor_result.prototype = {};
ManagementService_deploySensor_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ManagementService_deploySensor_result.prototype.write = function(output) {
  output.writeStructBegin('ManagementService_deploySensor_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ManagementService_addHost_args = function(args) {
  this.hostname = null;
  if (args) {
    if (args.hostname !== undefined) {
      this.hostname = args.hostname;
    }
  }
};
ManagementService_addHost_args.prototype = {};
ManagementService_addHost_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.hostname = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ManagementService_addHost_args.prototype.write = function(output) {
  output.writeStructBegin('ManagementService_addHost_args');
  if (this.hostname) {
    output.writeFieldBegin('hostname', Thrift.Type.STRING, 1);
    output.writeString(this.hostname);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ManagementService_addHost_result = function(args) {
};
ManagementService_addHost_result.prototype = {};
ManagementService_addHost_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ManagementService_addHost_result.prototype.write = function(output) {
  output.writeStructBegin('ManagementService_addHost_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ManagementService_delHost_args = function(args) {
  this.hostname = null;
  if (args) {
    if (args.hostname !== undefined) {
      this.hostname = args.hostname;
    }
  }
};
ManagementService_delHost_args.prototype = {};
ManagementService_delHost_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.hostname = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ManagementService_delHost_args.prototype.write = function(output) {
  output.writeStructBegin('ManagementService_delHost_args');
  if (this.hostname) {
    output.writeFieldBegin('hostname', Thrift.Type.STRING, 1);
    output.writeString(this.hostname);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ManagementService_delHost_result = function(args) {
};
ManagementService_delHost_result.prototype = {};
ManagementService_delHost_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ManagementService_delHost_result.prototype.write = function(output) {
  output.writeStructBegin('ManagementService_delHost_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ManagementService_setHostLabels_args = function(args) {
  this.hostname = null;
  this.labels = null;
  if (args) {
    if (args.hostname !== undefined) {
      this.hostname = args.hostname;
    }
    if (args.labels !== undefined) {
      this.labels = args.labels;
    }
  }
};
ManagementService_setHostLabels_args.prototype = {};
ManagementService_setHostLabels_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.hostname = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.SET) {
        var _size48 = 0;
        var _rtmp352;
        this.labels = [];
        var _etype51 = 0;
        _rtmp352 = input.readSetBegin();
        _etype51 = _rtmp352.etype;
        _size48 = _rtmp352.size;
        for (var _i53 = 0; _i53 < _size48; ++_i53)
        {
          var elem54 = null;
          elem54 = input.readString();
          this.labels.push(elem54);
        }
        input.readSetEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ManagementService_setHostLabels_args.prototype.write = function(output) {
  output.writeStructBegin('ManagementService_setHostLabels_args');
  if (this.hostname) {
    output.writeFieldBegin('hostname', Thrift.Type.STRING, 1);
    output.writeString(this.hostname);
    output.writeFieldEnd();
  }
  if (this.labels) {
    output.writeFieldBegin('labels', Thrift.Type.SET, 2);
    output.writeSetBegin(Thrift.Type.STRING, this.labels.length);
    for (var iter55 in this.labels)
    {
      if (this.labels.hasOwnProperty(iter55))
      {
        iter55 = this.labels[iter55];
        output.writeString(iter55);
      }
    }
    output.writeSetEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ManagementService_setHostLabels_result = function(args) {
};
ManagementService_setHostLabels_result.prototype = {};
ManagementService_setHostLabels_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ManagementService_setHostLabels_result.prototype.write = function(output) {
  output.writeStructBegin('ManagementService_setHostLabels_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ManagementService_getLabels_args = function(args) {
  this.hostname = null;
  if (args) {
    if (args.hostname !== undefined) {
      this.hostname = args.hostname;
    }
  }
};
ManagementService_getLabels_args.prototype = {};
ManagementService_getLabels_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.hostname = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ManagementService_getLabels_args.prototype.write = function(output) {
  output.writeStructBegin('ManagementService_getLabels_args');
  if (this.hostname) {
    output.writeFieldBegin('hostname', Thrift.Type.STRING, 1);
    output.writeString(this.hostname);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ManagementService_getLabels_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
ManagementService_getLabels_result.prototype = {};
ManagementService_getLabels_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.SET) {
        var _size56 = 0;
        var _rtmp360;
        this.success = [];
        var _etype59 = 0;
        _rtmp360 = input.readSetBegin();
        _etype59 = _rtmp360.etype;
        _size56 = _rtmp360.size;
        for (var _i61 = 0; _i61 < _size56; ++_i61)
        {
          var elem62 = null;
          elem62 = input.readString();
          this.success.push(elem62);
        }
        input.readSetEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ManagementService_getLabels_result.prototype.write = function(output) {
  output.writeStructBegin('ManagementService_getLabels_result');
  if (this.success) {
    output.writeFieldBegin('success', Thrift.Type.SET, 0);
    output.writeSetBegin(Thrift.Type.STRING, this.success.length);
    for (var iter63 in this.success)
    {
      if (this.success.hasOwnProperty(iter63))
      {
        iter63 = this.success[iter63];
        output.writeString(iter63);
      }
    }
    output.writeSetEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ManagementService_setSensor_args = function(args) {
  this.hostname = null;
  this.sensor = null;
  this.activate = null;
  if (args) {
    if (args.hostname !== undefined) {
      this.hostname = args.hostname;
    }
    if (args.sensor !== undefined) {
      this.sensor = args.sensor;
    }
    if (args.activate !== undefined) {
      this.activate = args.activate;
    }
  }
};
ManagementService_setSensor_args.prototype = {};
ManagementService_setSensor_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.hostname = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.sensor = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.BOOL) {
        this.activate = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ManagementService_setSensor_args.prototype.write = function(output) {
  output.writeStructBegin('ManagementService_setSensor_args');
  if (this.hostname) {
    output.writeFieldBegin('hostname', Thrift.Type.STRING, 1);
    output.writeString(this.hostname);
    output.writeFieldEnd();
  }
  if (this.sensor) {
    output.writeFieldBegin('sensor', Thrift.Type.STRING, 2);
    output.writeString(this.sensor);
    output.writeFieldEnd();
  }
  if (this.activate) {
    output.writeFieldBegin('activate', Thrift.Type.BOOL, 3);
    output.writeBool(this.activate);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ManagementService_setSensor_result = function(args) {
};
ManagementService_setSensor_result.prototype = {};
ManagementService_setSensor_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ManagementService_setSensor_result.prototype.write = function(output) {
  output.writeStructBegin('ManagementService_setSensor_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ManagementService_setSensorLabels_args = function(args) {
  this.sensor = null;
  this.labels = null;
  if (args) {
    if (args.sensor !== undefined) {
      this.sensor = args.sensor;
    }
    if (args.labels !== undefined) {
      this.labels = args.labels;
    }
  }
};
ManagementService_setSensorLabels_args.prototype = {};
ManagementService_setSensorLabels_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.sensor = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.SET) {
        var _size64 = 0;
        var _rtmp368;
        this.labels = [];
        var _etype67 = 0;
        _rtmp368 = input.readSetBegin();
        _etype67 = _rtmp368.etype;
        _size64 = _rtmp368.size;
        for (var _i69 = 0; _i69 < _size64; ++_i69)
        {
          var elem70 = null;
          elem70 = input.readString();
          this.labels.push(elem70);
        }
        input.readSetEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ManagementService_setSensorLabels_args.prototype.write = function(output) {
  output.writeStructBegin('ManagementService_setSensorLabels_args');
  if (this.sensor) {
    output.writeFieldBegin('sensor', Thrift.Type.STRING, 1);
    output.writeString(this.sensor);
    output.writeFieldEnd();
  }
  if (this.labels) {
    output.writeFieldBegin('labels', Thrift.Type.SET, 3);
    output.writeSetBegin(Thrift.Type.STRING, this.labels.length);
    for (var iter71 in this.labels)
    {
      if (this.labels.hasOwnProperty(iter71))
      {
        iter71 = this.labels[iter71];
        output.writeString(iter71);
      }
    }
    output.writeSetEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ManagementService_setSensorLabels_result = function(args) {
};
ManagementService_setSensorLabels_result.prototype = {};
ManagementService_setSensorLabels_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ManagementService_setSensorLabels_result.prototype.write = function(output) {
  output.writeStructBegin('ManagementService_setSensorLabels_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ManagementService_getSensorLabels_args = function(args) {
  this.sensor = null;
  if (args) {
    if (args.sensor !== undefined) {
      this.sensor = args.sensor;
    }
  }
};
ManagementService_getSensorLabels_args.prototype = {};
ManagementService_getSensorLabels_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.sensor = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ManagementService_getSensorLabels_args.prototype.write = function(output) {
  output.writeStructBegin('ManagementService_getSensorLabels_args');
  if (this.sensor) {
    output.writeFieldBegin('sensor', Thrift.Type.STRING, 1);
    output.writeString(this.sensor);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ManagementService_getSensorLabels_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
ManagementService_getSensorLabels_result.prototype = {};
ManagementService_getSensorLabels_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.SET) {
        var _size72 = 0;
        var _rtmp376;
        this.success = [];
        var _etype75 = 0;
        _rtmp376 = input.readSetBegin();
        _etype75 = _rtmp376.etype;
        _size72 = _rtmp376.size;
        for (var _i77 = 0; _i77 < _size72; ++_i77)
        {
          var elem78 = null;
          elem78 = input.readString();
          this.success.push(elem78);
        }
        input.readSetEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ManagementService_getSensorLabels_result.prototype.write = function(output) {
  output.writeStructBegin('ManagementService_getSensorLabels_result');
  if (this.success) {
    output.writeFieldBegin('success', Thrift.Type.SET, 0);
    output.writeSetBegin(Thrift.Type.STRING, this.success.length);
    for (var iter79 in this.success)
    {
      if (this.success.hasOwnProperty(iter79))
      {
        iter79 = this.success[iter79];
        output.writeString(iter79);
      }
    }
    output.writeSetEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ManagementService_setSensorConfiguration_args = function(args) {
  this.sensor = null;
  this.configuration = null;
  if (args) {
    if (args.sensor !== undefined) {
      this.sensor = args.sensor;
    }
    if (args.configuration !== undefined) {
      this.configuration = args.configuration;
    }
  }
};
ManagementService_setSensorConfiguration_args.prototype = {};
ManagementService_setSensorConfiguration_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.sensor = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.configuration = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ManagementService_setSensorConfiguration_args.prototype.write = function(output) {
  output.writeStructBegin('ManagementService_setSensorConfiguration_args');
  if (this.sensor) {
    output.writeFieldBegin('sensor', Thrift.Type.STRING, 1);
    output.writeString(this.sensor);
    output.writeFieldEnd();
  }
  if (this.configuration) {
    output.writeFieldBegin('configuration', Thrift.Type.STRING, 2);
    output.writeString(this.configuration);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ManagementService_setSensorConfiguration_result = function(args) {
};
ManagementService_setSensorConfiguration_result.prototype = {};
ManagementService_setSensorConfiguration_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ManagementService_setSensorConfiguration_result.prototype.write = function(output) {
  output.writeStructBegin('ManagementService_setSensorConfiguration_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ManagementService_getBundledSensorConfiguration_args = function(args) {
  this.sensor = null;
  this.hostname = null;
  if (args) {
    if (args.sensor !== undefined) {
      this.sensor = args.sensor;
    }
    if (args.hostname !== undefined) {
      this.hostname = args.hostname;
    }
  }
};
ManagementService_getBundledSensorConfiguration_args.prototype = {};
ManagementService_getBundledSensorConfiguration_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.sensor = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.hostname = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ManagementService_getBundledSensorConfiguration_args.prototype.write = function(output) {
  output.writeStructBegin('ManagementService_getBundledSensorConfiguration_args');
  if (this.sensor) {
    output.writeFieldBegin('sensor', Thrift.Type.STRING, 1);
    output.writeString(this.sensor);
    output.writeFieldEnd();
  }
  if (this.hostname) {
    output.writeFieldBegin('hostname', Thrift.Type.STRING, 2);
    output.writeString(this.hostname);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ManagementService_getBundledSensorConfiguration_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
ManagementService_getBundledSensorConfiguration_result.prototype = {};
ManagementService_getBundledSensorConfiguration_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.BundledSensorConfiguration();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ManagementService_getBundledSensorConfiguration_result.prototype.write = function(output) {
  output.writeStructBegin('ManagementService_getBundledSensorConfiguration_result');
  if (this.success) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ManagementServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {};
};
ManagementServiceClient.prototype = {};
ManagementServiceClient.prototype.query = function(query, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_query(query);
};

ManagementServiceClient.prototype.send_query = function(query) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('query', Thrift.MessageType.CALL, this.seqid);
  var args = new ManagementService_query_args();
  args.query = query;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ManagementServiceClient.prototype.recv_query = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ManagementService_query_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('query failed: unknown result');
};
ManagementServiceClient.prototype.fetchSensor = function(name, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_fetchSensor(name);
};

ManagementServiceClient.prototype.send_fetchSensor = function(name) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('fetchSensor', Thrift.MessageType.CALL, this.seqid);
  var args = new ManagementService_fetchSensor_args();
  args.name = name;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ManagementServiceClient.prototype.recv_fetchSensor = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ManagementService_fetchSensor_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('fetchSensor failed: unknown result');
};
ManagementServiceClient.prototype.deploySensor = function(name, file, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_deploySensor(name, file);
};

ManagementServiceClient.prototype.send_deploySensor = function(name, file) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('deploySensor', Thrift.MessageType.CALL, this.seqid);
  var args = new ManagementService_deploySensor_args();
  args.name = name;
  args.file = file;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ManagementServiceClient.prototype.recv_deploySensor = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ManagementService_deploySensor_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
ManagementServiceClient.prototype.addHost = function(hostname, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_addHost(hostname);
};

ManagementServiceClient.prototype.send_addHost = function(hostname) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('addHost', Thrift.MessageType.CALL, this.seqid);
  var args = new ManagementService_addHost_args();
  args.hostname = hostname;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ManagementServiceClient.prototype.recv_addHost = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ManagementService_addHost_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
ManagementServiceClient.prototype.delHost = function(hostname, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_delHost(hostname);
};

ManagementServiceClient.prototype.send_delHost = function(hostname) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('delHost', Thrift.MessageType.CALL, this.seqid);
  var args = new ManagementService_delHost_args();
  args.hostname = hostname;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ManagementServiceClient.prototype.recv_delHost = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ManagementService_delHost_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
ManagementServiceClient.prototype.setHostLabels = function(hostname, labels, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_setHostLabels(hostname, labels);
};

ManagementServiceClient.prototype.send_setHostLabels = function(hostname, labels) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('setHostLabels', Thrift.MessageType.CALL, this.seqid);
  var args = new ManagementService_setHostLabels_args();
  args.hostname = hostname;
  args.labels = labels;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ManagementServiceClient.prototype.recv_setHostLabels = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ManagementService_setHostLabels_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
ManagementServiceClient.prototype.getLabels = function(hostname, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_getLabels(hostname);
};

ManagementServiceClient.prototype.send_getLabels = function(hostname) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getLabels', Thrift.MessageType.CALL, this.seqid);
  var args = new ManagementService_getLabels_args();
  args.hostname = hostname;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ManagementServiceClient.prototype.recv_getLabels = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ManagementService_getLabels_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getLabels failed: unknown result');
};
ManagementServiceClient.prototype.setSensor = function(hostname, sensor, activate, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_setSensor(hostname, sensor, activate);
};

ManagementServiceClient.prototype.send_setSensor = function(hostname, sensor, activate) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('setSensor', Thrift.MessageType.CALL, this.seqid);
  var args = new ManagementService_setSensor_args();
  args.hostname = hostname;
  args.sensor = sensor;
  args.activate = activate;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ManagementServiceClient.prototype.recv_setSensor = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ManagementService_setSensor_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
ManagementServiceClient.prototype.setSensorLabels = function(sensor, labels, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_setSensorLabels(sensor, labels);
};

ManagementServiceClient.prototype.send_setSensorLabels = function(sensor, labels) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('setSensorLabels', Thrift.MessageType.CALL, this.seqid);
  var args = new ManagementService_setSensorLabels_args();
  args.sensor = sensor;
  args.labels = labels;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ManagementServiceClient.prototype.recv_setSensorLabels = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ManagementService_setSensorLabels_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
ManagementServiceClient.prototype.getSensorLabels = function(sensor, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_getSensorLabels(sensor);
};

ManagementServiceClient.prototype.send_getSensorLabels = function(sensor) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getSensorLabels', Thrift.MessageType.CALL, this.seqid);
  var args = new ManagementService_getSensorLabels_args();
  args.sensor = sensor;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ManagementServiceClient.prototype.recv_getSensorLabels = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ManagementService_getSensorLabels_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getSensorLabels failed: unknown result');
};
ManagementServiceClient.prototype.setSensorConfiguration = function(sensor, configuration, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_setSensorConfiguration(sensor, configuration);
};

ManagementServiceClient.prototype.send_setSensorConfiguration = function(sensor, configuration) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('setSensorConfiguration', Thrift.MessageType.CALL, this.seqid);
  var args = new ManagementService_setSensorConfiguration_args();
  args.sensor = sensor;
  args.configuration = configuration;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ManagementServiceClient.prototype.recv_setSensorConfiguration = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ManagementService_setSensorConfiguration_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
ManagementServiceClient.prototype.getBundledSensorConfiguration = function(sensor, hostname, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_getBundledSensorConfiguration(sensor, hostname);
};

ManagementServiceClient.prototype.send_getBundledSensorConfiguration = function(sensor, hostname) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getBundledSensorConfiguration', Thrift.MessageType.CALL, this.seqid);
  var args = new ManagementService_getBundledSensorConfiguration_args();
  args.sensor = sensor;
  args.hostname = hostname;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ManagementServiceClient.prototype.recv_getBundledSensorConfiguration = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ManagementService_getBundledSensorConfiguration_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getBundledSensorConfiguration failed: unknown result');
};
var ManagementServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
ManagementServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

ManagementServiceProcessor.prototype.process_query = function(seqid, input, output) {
  var args = new ManagementService_query_args();
  args.read(input);
  input.readMessageEnd();
  var result = new ManagementService_query_result();
  this._handler.query(args.query, function (success) {
    result.success = success;
    output.writeMessageBegin("query", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

ManagementServiceProcessor.prototype.process_fetchSensor = function(seqid, input, output) {
  var args = new ManagementService_fetchSensor_args();
  args.read(input);
  input.readMessageEnd();
  var result = new ManagementService_fetchSensor_result();
  this._handler.fetchSensor(args.name, function (success) {
    result.success = success;
    output.writeMessageBegin("fetchSensor", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

ManagementServiceProcessor.prototype.process_deploySensor = function(seqid, input, output) {
  var args = new ManagementService_deploySensor_args();
  args.read(input);
  input.readMessageEnd();
  var result = new ManagementService_deploySensor_result();
  this._handler.deploySensor(args.name, args.file, function (success) {
    result.success = success;
    output.writeMessageBegin("deploySensor", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

ManagementServiceProcessor.prototype.process_addHost = function(seqid, input, output) {
  var args = new ManagementService_addHost_args();
  args.read(input);
  input.readMessageEnd();
  var result = new ManagementService_addHost_result();
  this._handler.addHost(args.hostname, function (success) {
    result.success = success;
    output.writeMessageBegin("addHost", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

ManagementServiceProcessor.prototype.process_delHost = function(seqid, input, output) {
  var args = new ManagementService_delHost_args();
  args.read(input);
  input.readMessageEnd();
  var result = new ManagementService_delHost_result();
  this._handler.delHost(args.hostname, function (success) {
    result.success = success;
    output.writeMessageBegin("delHost", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

ManagementServiceProcessor.prototype.process_setHostLabels = function(seqid, input, output) {
  var args = new ManagementService_setHostLabels_args();
  args.read(input);
  input.readMessageEnd();
  var result = new ManagementService_setHostLabels_result();
  this._handler.setHostLabels(args.hostname, args.labels, function (success) {
    result.success = success;
    output.writeMessageBegin("setHostLabels", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

ManagementServiceProcessor.prototype.process_getLabels = function(seqid, input, output) {
  var args = new ManagementService_getLabels_args();
  args.read(input);
  input.readMessageEnd();
  var result = new ManagementService_getLabels_result();
  this._handler.getLabels(args.hostname, function (success) {
    result.success = success;
    output.writeMessageBegin("getLabels", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

ManagementServiceProcessor.prototype.process_setSensor = function(seqid, input, output) {
  var args = new ManagementService_setSensor_args();
  args.read(input);
  input.readMessageEnd();
  var result = new ManagementService_setSensor_result();
  this._handler.setSensor(args.hostname, args.sensor, args.activate, function (success) {
    result.success = success;
    output.writeMessageBegin("setSensor", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

ManagementServiceProcessor.prototype.process_setSensorLabels = function(seqid, input, output) {
  var args = new ManagementService_setSensorLabels_args();
  args.read(input);
  input.readMessageEnd();
  var result = new ManagementService_setSensorLabels_result();
  this._handler.setSensorLabels(args.sensor, args.labels, function (success) {
    result.success = success;
    output.writeMessageBegin("setSensorLabels", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

ManagementServiceProcessor.prototype.process_getSensorLabels = function(seqid, input, output) {
  var args = new ManagementService_getSensorLabels_args();
  args.read(input);
  input.readMessageEnd();
  var result = new ManagementService_getSensorLabels_result();
  this._handler.getSensorLabels(args.sensor, function (success) {
    result.success = success;
    output.writeMessageBegin("getSensorLabels", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

ManagementServiceProcessor.prototype.process_setSensorConfiguration = function(seqid, input, output) {
  var args = new ManagementService_setSensorConfiguration_args();
  args.read(input);
  input.readMessageEnd();
  var result = new ManagementService_setSensorConfiguration_result();
  this._handler.setSensorConfiguration(args.sensor, args.configuration, function (success) {
    result.success = success;
    output.writeMessageBegin("setSensorConfiguration", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

ManagementServiceProcessor.prototype.process_getBundledSensorConfiguration = function(seqid, input, output) {
  var args = new ManagementService_getBundledSensorConfiguration_args();
  args.read(input);
  input.readMessageEnd();
  var result = new ManagementService_getBundledSensorConfiguration_result();
  this._handler.getBundledSensorConfiguration(args.sensor, args.hostname, function (success) {
    result.success = success;
    output.writeMessageBegin("getBundledSensorConfiguration", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

