# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='trace.proto',
  package='de.tum.in.dss.dbound',
  serialized_pb='\n\x0btrace.proto\x12\x14\x64\x65.tum.in.dss.dbound\"\x83\x01\n\x05Trace\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x35\n\x08\x65lements\x18\x02 \x03(\x0b\x32#.de.tum.in.dss.dbound.Trace.Element\x1a\x35\n\x07\x45lement\x12\r\n\x05start\x18\x01 \x02(\x04\x12\x0c\n\x04stop\x18\x02 \x02(\x04\x12\r\n\x05value\x18\x03 \x02(\x01')




_TRACE_ELEMENT = descriptor.Descriptor(
  name='Element',
  full_name='de.tum.in.dss.dbound.Trace.Element',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='start', full_name='de.tum.in.dss.dbound.Trace.Element.start', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stop', full_name='de.tum.in.dss.dbound.Trace.Element.stop', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='de.tum.in.dss.dbound.Trace.Element.value', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=116,
  serialized_end=169,
)

_TRACE = descriptor.Descriptor(
  name='Trace',
  full_name='de.tum.in.dss.dbound.Trace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='de.tum.in.dss.dbound.Trace.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='elements', full_name='de.tum.in.dss.dbound.Trace.elements', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TRACE_ELEMENT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=38,
  serialized_end=169,
)

_TRACE_ELEMENT.containing_type = _TRACE;
_TRACE.fields_by_name['elements'].message_type = _TRACE_ELEMENT
DESCRIPTOR.message_types_by_name['Trace'] = _TRACE

class Trace(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Element(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _TRACE_ELEMENT
    
    # @@protoc_insertion_point(class_scope:de.tum.in.dss.dbound.Trace.Element)
  DESCRIPTOR = _TRACE
  
  # @@protoc_insertion_point(class_scope:de.tum.in.dss.dbound.Trace)

# @@protoc_insertion_point(module_scope)
